ALTER TYPE "ProceduralEventType" ADD VALUE IF NOT EXISTS 'PERICIA_MEDICA_ADMINISTRATIVA';
ALTER TYPE "ProceduralEventType" ADD VALUE IF NOT EXISTS 'PERICIA_SOCIAL_ADMINISTRATIVA';
ALTER TYPE "ProceduralEventType" ADD VALUE IF NOT EXISTS 'PERICIA_MEDICA_JUDICIAL';
ALTER TYPE "ProceduralEventType" ADD VALUE IF NOT EXISTS 'PERICIA_SOCIAL_JUDICIAL';
