export enum UserRole {
  ADMIN = "ADMIN",
  ADVOGADO = "ADVOGADO",
  ASSISTENTE = "ASSISTENTE",
  LEITURA = "LEITURA"
}

export enum Gender {
  FEMININO = "FEMININO",
  MASCULINO = "MASCULINO",
  OUTRO = "OUTRO",
  NAO_INFORMADO = "NAO_INFORMADO"
}

export enum ChannelType {
  ADMINISTRATIVO = "ADMINISTRATIVO",
  JUDICIAL = "JUDICIAL"
}

export enum BenefitType {
  AUXILIO_DOENCA = "AUXILIO_DOENCA",
  APOSENTADORIA_INCAPACIDADE = "APOSENTADORIA_INCAPACIDADE",
  BPC_LOAS = "BPC_LOAS",
  OUTRO = "OUTRO"
}

export enum CaseStatus {
  EM_ANALISE = "EM_ANALISE",
  AGUARDANDO_DOCUMENTOS = "AGUARDANDO_DOCUMENTOS",
  EM_PERICIA = "EM_PERICIA",
  AGUARDANDO_DECISAO = "AGUARDANDO_DECISAO",
  CONCLUIDO = "CONCLUIDO",
  ARQUIVADO = "ARQUIVADO"
}

export enum StrengthLevel {
  FRACA = "FRACA",
  MEDIA = "MEDIA",
  FORTE = "FORTE"
}

export enum RiskLevel {
  BAIXO = "BAIXO",
  MEDIO = "MEDIO",
  ALTO = "ALTO"
}

export enum ProceduralEventType {
  PROTOCOLO = "PROTOCOLO",
  PERICIA_ADMINISTRATIVA = "PERICIA_ADMINISTRATIVA",
  DECISAO_ADMINISTRATIVA = "DECISAO_ADMINISTRATIVA",
  AJUIZAMENTO = "AJUIZAMENTO",
  PERICIA_JUDICIAL = "PERICIA_JUDICIAL",
  SENTENCA = "SENTENCA",
  RECURSO = "RECURSO",
  ACORDAO = "ACORDAO",
  CUMPRIMENTO = "CUMPRIMENTO",
  OUTRO = "OUTRO"
}

export enum OutcomeStatus {
  DEFERIDO = "DEFERIDO",
  INDEFERIDO = "INDEFERIDO",
  PROCEDENTE = "PROCEDENTE",
  IMPROCEDENTE = "IMPROCEDENTE",
  PARCIALMENTE_PROCEDENTE = "PARCIALMENTE_PROCEDENTE",
  ACORDO = "ACORDO",
  PENDENTE = "PENDENTE"
}

export enum OCRStatus {
  PENDENTE = "PENDENTE",
  PROCESSANDO = "PROCESSANDO",
  CONCLUIDO = "CONCLUIDO",
  FALHOU = "FALHOU"
}

export enum AIStatus {
  NAO_INICIADO = "NAO_INICIADO",
  PENDENTE_REVISAO = "PENDENTE_REVISAO",
  APROVADO = "APROVADO",
  REJEITADO = "REJEITADO"
}

export enum ExtractionSourceType {
  MANUAL = "MANUAL",
  AI = "AI",
  OCR_E_AI = "OCR_E_AI"
}

export enum IncapacityScope {
  TOTAL = "TOTAL",
  PARCIAL = "PARCIAL",
  NAO_INFORMADO = "NAO_INFORMADO"
}

export enum IncapacityDuration {
  TEMPORARIA = "TEMPORARIA",
  PERMANENTE = "PERMANENTE",
  NAO_INFORMADO = "NAO_INFORMADO"
}

export enum AttendanceKind {
  CONSULTA_INICIAL = "CONSULTA_INICIAL",
  RETORNO = "RETORNO",
  TRIAGEM_DOCUMENTAL = "TRIAGEM_DOCUMENTAL",
  ESTRATEGIA_PROCESSUAL = "ESTRATEGIA_PROCESSUAL",
  POS_DECISAO = "POS_DECISAO"
}
